server:
  port: 8084
spring:
  datasource:
    username: root
    password: MYSQL2151294
    #url中database为对应的数据库名称
    url: jdbc:mysql://localhost:3306/ji_tickets?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.edu.tongji.springbackend.model
file:
  upload:
    society-logo-dir: D:\\软件工程项目\\backend\\upload_images\\society_logo\\
    society-image-dir: D:\\软件工程项目\\backend\\upload_images\\society_image\\
    appeal-image-dir: D:\软件工程项目\appeal-image\

